### ISSUE TITLE
Incompatible FML modded server

### ISSUE THREAD

**Issue by F0x06** [tr7zw/EntityCulling-Forge#1]
Hi, first thanks for this awesome mod ! 

the mod is not flagges as a client-only mod, resulting mod list checking when connecting to a server, 

![image](https://user-images.githubusercontent.com/7167311/110225628-af635580-7ee7-11eb-9dbb-61668f88347b.png)

Can be fixed like that on the mod initializer `EntityCullingMod()`
```java
import net.minecraftforge.fml.ExtensionPoint;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.network.FMLNetworkConstants;
import org.apache.commons.lang3.tuple.Pair;

ModLoadingContext.get().registerExtensionPoint(ExtensionPoint.DISPLAYTEST, () -> Pair.of(() -> FMLNetworkConstants.IGNORESERVERONLY, (remote, isServer) -> true));
````

Thanks.

**Comment by tr7zw** [comment]
Ah thanks, I'll add this to my Forge mods.
