### ISSUE TITLE
Server freeze with pokecube aio mod

### ISSUE THREAD

**Issue by chengts95** [tr7zw/EntityCulling-Forge#3]
Hello, I find a bug with [pokecube aio](https://github.com/Pokecube-Development) mod. When the pokemon is using a move, the move particle effect cannot show, and the server freezes for seconds. In the other [entity culling](https://www.curseforge.com/minecraft/mc-mods/entity-culling) mod everything is normal, is it possible to fix it? Thank you!

**Comment by tr7zw** [comment]
This is not a server mod. So it didn't even load on the server?!?

**Comment by chengts95** [comment]
yes but on the client, I observe the server lag since single-play uses the internal server, no error reported. Maybe the algorithm hangs up when handling the pokecube particle effects. On the dedicated server, I think only the client freezes.

**Comment by tr7zw** [comment]
The mod does nothing with particles at all. And also nothing with the internal server. The only thing that might be happening is that the mod has a giant hitbox on something that causes an issue on the currently released version. In that case, you could try the newest build under Actions that has a limit on the size of the hitbox.

**Comment by chengts95** [comment]
OK, I can test it when I am free.

**Comment by chengts95** [comment]
I have tried the latest build and the problem is fixed,  thank you very much! I am going to close this issue.
