### ISSUE TITLE
[1.16.5- Forge] If mod is loaded on server It'll crash. (more in description)

### ISSUE THREAD

**Issue by Gbergz** [tr7zw/EntityCulling-Forge#4]
Title^

If the mod is loaded on a server It'll crash, and ontop of that would it be possible to add a check for when running on server/client? Just so it doesn't mark the server as an Incompatible FML Modded Server if mod is not present on the server.

![image](https://user-images.githubusercontent.com/26634554/119144181-b4e12e00-ba48-11eb-9771-92c405afdbcd.png)

Version: [1.2.2](https://www.curseforge.com/minecraft/mc-mods/entityculling/files/3296216)

Crash-Report: https://gist.github.com/Gbergz/a579e4d8320994de13be62de7aa62250

**Comment by tr7zw** [comment]
Huh looks like I forgot to add the line that marks it to be ignored in this server compatibility check. And yes this is not a server mod!

**Comment by Gbergz** [comment]
Any ETA on a release with the fix for "Incompatible FML modded server" issue? No rush ofcourse.

**Comment by tr7zw** [comment]
Well, it is a purely visual bug, and currently more concerned with the cache issues like https://github.com/tr7zw/EntityCulling-Fabric/issues/28 , and busy with uni tasks. The next release will have this fixed.
